name: Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint black

    - name: Formatting with black
      run: |
        black $(git ls-files '*.py')
    
    - name: Commit changes
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add .
        git commit -m "Format code with Black" || echo "No changes to commit"

    - name: Analysing with pylint
      run: |
        pylint --disable=import-error --exit-zero $(git ls-files '*.py')
