name: Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
  
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black isort
  
      - name: Check if last commit was by github-actions
        id: skip
        run: |
          if [ "$(git log -1 --pretty=format:'%an')" = "github-actions" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
  
      - name: Formatting with black
        if: steps.skip.outputs.skip != 'true'
        run: |
          isort $(git ls-files '*.py')
          black $(git ls-files '*.py')
  
      - name: Commit changes
        if: steps.skip.outputs.skip != 'true'
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add .
          git commit -m "Format code with Black" || echo "No changes to commit"
  
      - name: Push changes
        if: steps.skip.outputs.skip != 'true'
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Analysing with pylint
        run: |
          pylint --disable=import-error --exit-zero $(git ls-files '*.py')
