name: Honest Price Feed Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour
  workflow_dispatch:      # Allows manual runs

jobs:
  run-honest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt install python3-dev pkg-config libffi-dev libsecp256k1-dev build-essential
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Honest Price Feed
        env:
          USERNAME: ${{ secrets.USERNAME }}
          WIF: ${{ secrets.WIF }}
        # TODO: review and add credentials; then add --publish
        run: python honest/HONEST.py --oneshot --headless
